# Uncomment the next line to define a global platform for your project

platform :ios, '10.0'
inhibit_all_warnings!
# use_frameworks!
workspace 'IdnowApp'

def hostAppPods

end

def sdkPods

end

def sharedPods
    pod 'SnapKit', '~> 4.0.0'
end

def autoIdentPods

end

def videoIdentPods
    pod 'Masonry', '~> 1.1.0'
end

target 'IdnowApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  project 'IdnowApp'

  # Pods for IdnowApp
  hostAppPods
  sharedPods

  target 'IdnowAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IdnowAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end


target 'IdnowSdk' do
    use_frameworks!
    project 'IdnowSdk/IdnowSdk/IdnowSdk'
    sdkPods
    sharedPods
    target 'IdnowSdkTests' do
        inherit! :search_paths
        # Pods for testing
    end
end

target 'AutoIdentSdk' do
    use_frameworks!
    project 'IdnowSdk/IdnowSdk/IdnowSdk/AutoIdentSdk/AutoIdentSdk/AutoIdentSdk'
    autoIdentPods
    sharedPods
    target 'AutoIdentSdkTests' do

        inherit! :search_paths
        # Pods for testing
    end
end

target 'VideoIdentSdk' do
    project 'IdnowSdk/IdnowSdk/IdnowSdk/VideoIdentSdk/VideoIdentSdk/VideoIdentSdk'
    videoIdentPods

end
